#!/bin/bash
### BEGIN INIT INFO
# Provides:          bsext-gaze
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: BrightSign Gaze Detection Extension
# Description:       Runs the BrightSign NPU-based gaze detection service
### END INIT INFO

# Source function library if it exists
[ -f /etc/init.d/functions ] && . /etc/init.d/functions

SCRIPT_NAME=start-ext.sh
SCRIPT_PATH=$(dirname $(realpath $0))
DAEMON_NAME="bsext-gaze"
PIDFILE="/var/run/${DAEMON_NAME}.pid"

do_start() {
    cd ${SCRIPT_PATH}
    start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} --exec $0 -- run
}

do_stop() {
    start-stop-daemon --stop --pidfile ${PIDFILE}
    rm -f ${PIDFILE}
}

case "$1" in
    start)
        echo "Starting ${DAEMON_NAME}"
        do_start
        ;;
    stop)
        echo "Stopping ${DAEMON_NAME}"
        do_stop
        ;;
    restart)
        echo "Restarting ${DAEMON_NAME}"
        do_stop
        do_start
        ;;
    run)
        # figure out the SOC model -- default to RK3588
        SOC_MODEL=RK3588
        if [ -f /sys/firmware/devicetree/base/compatible ]; then
            SOC_MODEL=$(cat /sys/firmware/devicetree/base/compatible | cut -d',' -f5 | tr '[:lower:]' '[:upper:]')
        else
            echo "WARNING: Unable to determine SOC model, EXITING"
            exit 1
        fi
        echo "SOC_MODEL: ${SOC_MODEL}"

        VID_DEVID=/dev/video0
        if [ "${SOC_MODEL}" = "RK3588" ]; then
            VID_DEVID=/dev/video1
        fi

        export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
        # run it
        ./attention_demo model/${SOC_MODEL}/RetinaFace.rknn ${VID_DEVID}
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|run}"
        exit 1
        ;;
esac

exit 0
